In [5]:
import numpy as np
from sklearn.metrics import r2_score

In [6]:
# calculating correlation scores

import scipy.stats


def evaluate_lists(pred, gold):
    if len(pred) == len(gold):
        gold_scores=gold
        pred_scores=pred         
        
        # lists storing gold and prediction scores where gold score >= 0.5
        gold_scores_range_05_1=[]
        pred_scores_range_05_1=[]
         
            
        for i in range(len(gold_scores)):
            if(gold_scores[i]>=0.5):
                gold_scores_range_05_1.append(gold_scores[i])
                pred_scores_range_05_1.append(pred_scores[i])
                
        # return zero correlation if predictions are constant
        if np.std(pred_scores)==0 or np.std(gold_scores)==0:
            return (0,0,0,0)
        
        pears_corr=scipy.stats.pearsonr(pred_scores,gold_scores)[0]                                    
        spear_corr=scipy.stats.spearmanr(pred_scores,gold_scores)[0]   


        pears_corr_range_05_1=scipy.stats.pearsonr(pred_scores_range_05_1,gold_scores_range_05_1)[0]                                    
        spear_corr_range_05_1=scipy.stats.spearmanr(pred_scores_range_05_1,gold_scores_range_05_1)[0]           
        
      
        return np.array([pears_corr,spear_corr,pears_corr_range_05_1,spear_corr_range_05_1])
    else:
        raise ValueError('Predictions and gold data have different number of lines.')

# Model based on Anger's training data

In [7]:
from keras_self_attention import SeqSelfAttention, SeqWeightedAttention
from keras.models import load_model
emotion = "anger"
neural_network_path = "files/final_models/" + "lstmatt_"+ emotion + ".h5"

model_a = load_model(neural_network_path, custom_objects=SeqWeightedAttention.get_custom_objects())

# model_a's input length is 25

Using TensorFlow backend.


# (1) Evaluate on Fear's testing data

In [101]:
x_test_path_f = "files/fear_vectors/x_test_lstmatt.npy"

In [103]:
import pickle
# restore vectors
with open(x_test_path_f, 'rb') as x_test_file_f:
    x_test_f = pickle.load(x_test_file_f)

In [104]:
x_test_f.shape

(995, 27)

In [11]:
x_test_f

array([[3837,  118,  118, ...,    0,    0,    0],
       [  29,   29, 1154, ...,    0,    0,    0],
       [ 621,  323, 3842, ...,    0,    0,    0],
       ...,
       [ 706, 2321,  963, ...,    0,    0,    0],
       [ 553,  592, 5076, ...,    0,    0,    0],
       [5402,  874,  398, ...,    0,    0,    0]])

In [12]:
i_list = []
for i in x_test_f.tolist():
    i = i[:25]
    i_list.append(i)
x_test_f_1 = np.array(i_list)
x_test_f_1.shape

(995, 25)

In [93]:
y_test_path_f = "files/fear_vectors/y_test_lstmatt.npy"

In [98]:
import pickle
# restore vectors
with open(y_test_path_f, 'rb') as y_test_file_f:
    y_gold_f = pickle.load(y_test_file_f)
    

In [15]:
y_pred_f = model_a.predict(x_test_f_1)

In [16]:
score1_af = evaluate_lists(np.concatenate(y_pred_f), y_gold_f)
score1_af

array([0.14427986, 0.14175294, 0.10240098, 0.07846169])

In [17]:
score2_af = r2_score( y_gold_f, np.concatenate(y_pred_f,axis=0))
score2_af

-0.2850225721957258

# (2) Evaluate on Joy's testing data

In [18]:
x_test_path_j = "files/joy_vectors/x_test_lstmatt.npy"

In [19]:
import pickle
# restore vectors
with open(x_test_path_j, 'rb') as x_test_file_j:
    x_test_j = pickle.load(x_test_file_j)

In [20]:
x_test_j.shape

(714, 29)

In [21]:
i_list = []
for i in x_test_j.tolist():
    i = i[:25]
    i_list.append(i)
x_test_j_1 = np.array(i_list)
x_test_j_1.shape

(714, 25)

In [22]:
y_test_path_j = "files/joy_vectors/y_test_lstmatt.npy"

In [23]:
import pickle
# restore vectors
with open(y_test_path_j, 'rb') as y_test_file_j:
    y_gold_j = pickle.load(y_test_file_j)

In [24]:
y_pred_j = model_a.predict(x_test_j_1)

In [25]:
score1_aj = evaluate_lists(np.concatenate(y_pred_j), y_gold_j)
score1_aj

array([0.13757419, 0.13776679, 0.05859923, 0.06599017])

In [27]:
score2_aj = r2_score( y_gold_j, np.concatenate(y_pred_j, axis=0))
score2_aj

-0.18889521454415314

# (3)  Evaluate on Sadness's testing data

In [28]:
x_test_path_s = "files/sadness_vectors/x_test_lstmatt.npy"

In [30]:
import pickle
# restore vectors
with open(x_test_path_s, 'rb') as x_test_file_s:
    x_test_s = pickle.load(x_test_file_s)

In [31]:
x_test_s.shape

(673, 32)

In [32]:
i_list = []
for i in x_test_s.tolist():
    i = i[:25]
    i_list.append(i)
x_test_s_1 = np.array(i_list)
x_test_s_1.shape

(673, 25)

In [35]:
y_test_path_s = "files/sadness_vectors/y_test_lstmatt.npy"

In [36]:
import pickle
# restore vectors
with open(y_test_path_s, 'rb') as y_test_file_s:
    y_gold_s = pickle.load(y_test_file_s)

In [37]:
y_pred_s = model_a.predict(x_test_s_1)

In [38]:
score1_as = evaluate_lists(np.concatenate(y_pred_s), y_gold_s)
score1_as

array([0.02880648, 0.01966332, 0.12801944, 0.10889506])

In [39]:
score2_as = r2_score( y_gold_s, np.concatenate(y_pred_s, axis=0))
score2_as

-0.441341718287555

# Model based on Fear's training data

In [58]:
from keras_self_attention import SeqSelfAttention, SeqWeightedAttention
from keras.models import load_model
emotion = "fear"
neural_network_path = "files/final_models/" + "lstmatt_"+ emotion + ".h5"

model_f = load_model(neural_network_path, custom_objects=SeqWeightedAttention.get_custom_objects())

# model_f's input length is 27

# (1) Evaluate on Anger's testing data

In [43]:
x_test_path_a = "files/anger_vectors/x_test_lstmatt.npy"

In [44]:
import pickle
# restore vectors
with open(x_test_path_a, 'rb') as x_test_file_a:
    x_test_a = pickle.load(x_test_file_a)

In [45]:
x_test_a.shape

(760, 25)

In [50]:
pad_a = np.zeros((760,2))

In [54]:
x_test_a_1 = np.concatenate((x_test_a, pad_a), axis=1)
x_test_a_1.shape

(760, 27)

In [55]:
y_test_path_a = "files/anger_vectors/y_test_lstmatt.npy"

In [56]:
import pickle
# restore vectors
with open(y_test_path_a, 'rb') as y_test_file_a:
    y_gold_a = pickle.load(y_test_file_a)

In [59]:
y_pred_a = model_f.predict(x_test_a_1)

In [60]:
score1_fa = evaluate_lists(np.concatenate(y_pred_a), y_gold_a)
score1_fa

array([0.17607785, 0.1633526 , 0.17587928, 0.15494419])

In [61]:
score2_fa = r2_score( y_gold_a, np.concatenate(y_pred_a, axis=0))
score2_fa

-0.5848817192637823

# (2) Evaluate on Joy's testing data

In [62]:
x_test_j.shape

(714, 29)

In [63]:
i_list = []
for i in x_test_j.tolist():
    i = i[:27]
    i_list.append(i)
x_test_j_2 = np.array(i_list)
x_test_j_2.shape

(714, 27)

In [66]:
y_pred_j = model_f.predict(x_test_j_2)

In [67]:
score1_fj = evaluate_lists(np.concatenate(y_pred_j), y_gold_j)
score1_fj

array([0.12795177, 0.13632302, 0.12148089, 0.12208705])

In [68]:
score2_fj = r2_score( y_gold_j, np.concatenate(y_pred_j, axis=0))
score2_fj

-0.6902312647159303

# (3) Evaluate on Sadness's testing data

In [69]:
x_test_path_s = "files/sadness_vectors/x_test_lstmatt.npy"

In [70]:
import pickle
# restore vectors
with open(x_test_path_s, 'rb') as x_test_file_s:
    x_test_s = pickle.load(x_test_file_s)

In [71]:
x_test_s.shape

(673, 32)

In [72]:
i_list = []
for i in x_test_s.tolist():
    i = i[:27]
    i_list.append(i)
x_test_s_2 = np.array(i_list)
x_test_s_2.shape

(673, 27)

In [73]:
y_test_path_s = "files/sadness_vectors/y_test_lstmatt.npy"

In [74]:
import pickle
# restore vectors
with open(y_test_path_s, 'rb') as y_test_file_s:
    y_gold_s = pickle.load(y_test_file_s)

In [75]:
y_pred_s = model_f.predict(x_test_s_2)

In [76]:
score1_fs = evaluate_lists(np.concatenate(y_pred_s), y_gold_s)
score1_fs

array([0.16275533, 0.15195597, 0.17263346, 0.16773367])

In [77]:
score2_fs = r2_score( y_gold_s, np.concatenate(y_pred_s,axis=0))
score2_fs

-0.3448358511186216

# Model based on Joy's training data

In [79]:
from keras_self_attention import SeqSelfAttention, SeqWeightedAttention
from keras.models import load_model
emotion = "joy"
neural_network_path = "files/final_models/" + "lstmatt_"+ emotion + ".h5"

model_j = load_model(neural_network_path, custom_objects=SeqWeightedAttention.get_custom_objects())

# model_j's input length is 29

# (1) Evaluate on Anger's testing data

In [78]:
x_test_a.shape

(760, 25)

In [80]:
pad_a = np.zeros((760,4))

x_test_a_2 = np.concatenate((x_test_a, pad_a), axis=1)
x_test_a_2.shape

(760, 29)

In [81]:
y_pred_a = model_j.predict(x_test_a_2)

In [82]:
score1_ja = evaluate_lists(np.concatenate(y_pred_a), y_gold_a)
score1_ja

array([0.20528835, 0.21191954, 0.14401007, 0.15577089])

In [83]:
score2_ja = r2_score( y_gold_a, np.concatenate(y_pred_a,axis=0))
score2_ja

-0.4849602699693303

# (2) Evaluate on Fear's testing data

In [105]:
x_test_f.shape

(995, 27)

In [110]:
pad_f = np.zeros((995,2))

x_test_f_2 = np.concatenate((x_test_f, pad_f), axis=1)
x_test_f_2.shape

(995, 29)

In [111]:
y_pred_f = model_j.predict(x_test_f_2)

In [112]:
y_pred_f.shape

(995, 1)

In [95]:
len(y_gold_f)

995

In [113]:
score1_jf = evaluate_lists(np.concatenate(y_pred_f), y_gold_f)
score1_jf

array([0.15833263, 0.14516126, 0.14015935, 0.11749486])

In [114]:
score2_fs = r2_score( y_gold_f, np.concatenate(y_pred_f,axis=0))
score2_fs

-0.4634936984201783

# (3) Evaluate on Sadness's testing data

In [117]:
x_test_s.shape

(673, 32)

In [120]:
i_list = []
for i in x_test_s.tolist():
    i = i[:29]
    i_list.append(i)
x_test_s_3 = np.array(i_list)
x_test_s_3.shape

(673, 29)

In [124]:
y_pred_s = model_j.predict(x_test_s_3)

In [125]:
score1_js = evaluate_lists(np.concatenate(y_pred_s), y_gold_s)
score1_js

array([0.13510827, 0.1260913 , 0.2544796 , 0.24690998])

In [126]:
score2_js = r2_score( y_gold_s, np.concatenate(y_pred_s,axis=0))
score2_js

-0.39528257841000225

# Model based on Sadness's training data

In [134]:
from keras_self_attention import SeqSelfAttention, SeqWeightedAttention
from keras.models import load_model
emotion = "sadness"
neural_network_path = "files/final_models/" + "lstmatt_"+ emotion + ".h5"

model_s = load_model(neural_network_path, custom_objects=SeqWeightedAttention.get_custom_objects())

# model_s's input length is 32

# (1) Evaluate on Anger's testing data

In [135]:
x_test_a.shape

(760, 25)

In [136]:
pad_a = np.zeros((760,7))

x_test_a_3 = np.concatenate((x_test_a, pad_a), axis=1)
x_test_a_3.shape

(760, 32)

In [137]:
y_pred_a = model_s.predict(x_test_a_3)

In [138]:
score1_sa = evaluate_lists(np.concatenate(y_pred_a), y_gold_a)
score1_sa

array([0.161729  , 0.16603149, 0.12425336, 0.14461773])

In [139]:
score2_sa = r2_score( y_gold_a, np.concatenate(y_pred_a,axis=0))
score2_sa

-0.4756695404539999

# (2) Evaluate on Fear's testing data¶

In [140]:
x_test_f.shape

(995, 27)

In [145]:
pad_f = np.zeros((995,5))

x_test_f_3 = np.concatenate((x_test_f, pad_f), axis=1)
x_test_f_3.shape

(995, 32)

In [146]:
y_pred_f = model_s.predict(x_test_f_3)

In [147]:
score1_sf = evaluate_lists(np.concatenate(y_pred_f), y_gold_f)
score1_sf

array([0.08482501, 0.06905951, 0.07885919, 0.04707761])

In [149]:
score2_sf = r2_score( y_gold_f, np.concatenate(y_pred_f,axis=0))
score2_sf

-0.7803125186933557

# (3) Evaluate on Joy's testing data¶

In [154]:
x_test_j.shape

(714, 29)

In [156]:
pad_j = np.zeros((714,3))

x_test_j_3 = np.concatenate((x_test_j, pad_j), axis=1)
x_test_j_3.shape

(714, 32)

In [157]:
y_pred_j = model_s.predict(x_test_j_3)

In [158]:
score1_sj = evaluate_lists(np.concatenate(y_pred_j), y_gold_j)
score1_sj

array([0.2104644 , 0.208948  , 0.11231986, 0.09934117])

In [159]:
score2_sj = r2_score( y_gold_j, np.concatenate(y_pred_j,axis=0))
score2_sj

-0.21042270379050354